name = "ToOpt3"
uuid = "fa21d375-5604-4f00-a1e1-496246133ddf"
authors = ["csellmann "]
version = "0.1.0"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Ju3VEM = "1347c348-1bfd-4c3d-8882-6b82a363c4f2"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PETSc = "ace2c81b-2b5f-4b1e-a30d-d662738edfe0"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AlgebraicMultigrid = "1.1.0"
ArgParse = "1.2.0"
Bumper = "0.7.1"
Chairmarks = "1.3.1"
Infiltrator = "1.9.4"
IterativeSolvers = "0.9.4"
JLD2 = "0.6.2"
MPI = "0.20.23"
OrderedCollections = "1.8.1"
PETSc = "0.3.1"
Pardiso = "1.1.0"
SparseArrays = "1.11.0"
StaticArrays = "1.9.15"
TimerOutputs = "0.5.29"
